[supervisord]
nodaemon=true
user=root

[program:mysqld]
command=/usr/sbin/mysqld
user=mysql
autostart=true
autorestart=true
stdout_logfile=/var/log/mysql.log
stderr_logfile=/var/log/mysql_err.log
priority=1

[program:apache2]
command=/bin/bash -c "rm -f /var/run/apache2/apache2.pid; exec /usr/sbin/apache2ctl -D FOREGROUND"
autostart=true
autorestart=true
stdout_logfile=/var/log/apache.log
stderr_logfile=/var/log/apache_err.log
priority=2